name: SaccadicEyeMovementNet
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
    - pandas
    - numpy
    - jupyterlab
    - tensorflow
    - tensorflow_datasets
    - tqdm
    - matplotlib
    - CocoDataset==0.1.2
